// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package com.weds.socket.protobuf;

public final class Command {
  private Command() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  /**
   * Protobuf enum {@code CommandType}
   *
   * <pre>
   * *
   * 指令类型
   * </pre>
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AUTH = 1;</code>
     *
     * <pre>
     * *
     * 认证
     * </pre>
     */
    AUTH(0, 1),
    /**
     * <code>PING = 2;</code>
     *
     * <pre>
     * *
     * 心跳
     * </pre>
     */
    PING(1, 2),
    /**
     * <code>PUSH_DATA = 3;</code>
     *
     * <pre>
     * *
     * 推送数据
     * </pre>
     */
    PUSH_DATA(2, 3),
    /**
     * <code>UPLOAD_DATA = 4;</code>
     *
     * <pre>
     * *
     * 上传数据
     * </pre>
     */
    UPLOAD_DATA(3, 4),
    /**
     * <code>AUTH_BACK = 11;</code>
     *
     * <pre>
     * *
     * 认证返回
     * </pre>
     */
    AUTH_BACK(4, 11),
    /**
     * <code>PONG = 12;</code>
     *
     * <pre>
     * *
     * 心跳返回
     * </pre>
     */
    PONG(5, 12),
    /**
     * <code>PUSH_DATA_BACK = 13;</code>
     */
    PUSH_DATA_BACK(6, 13),
    /**
     * <code>UPLOAD_DATA_BACK = 14;</code>
     */
    UPLOAD_DATA_BACK(7, 14),
    ;

    /**
     * <code>AUTH = 1;</code>
     *
     * <pre>
     * *
     * 认证
     * </pre>
     */
    public static final int AUTH_VALUE = 1;
    /**
     * <code>PING = 2;</code>
     *
     * <pre>
     * *
     * 心跳
     * </pre>
     */
    public static final int PING_VALUE = 2;
    /**
     * <code>PUSH_DATA = 3;</code>
     *
     * <pre>
     * *
     * 推送数据
     * </pre>
     */
    public static final int PUSH_DATA_VALUE = 3;
    /**
     * <code>UPLOAD_DATA = 4;</code>
     *
     * <pre>
     * *
     * 上传数据
     * </pre>
     */
    public static final int UPLOAD_DATA_VALUE = 4;
    /**
     * <code>AUTH_BACK = 11;</code>
     *
     * <pre>
     * *
     * 认证返回
     * </pre>
     */
    public static final int AUTH_BACK_VALUE = 11;
    /**
     * <code>PONG = 12;</code>
     *
     * <pre>
     * *
     * 心跳返回
     * </pre>
     */
    public static final int PONG_VALUE = 12;
    /**
     * <code>PUSH_DATA_BACK = 13;</code>
     */
    public static final int PUSH_DATA_BACK_VALUE = 13;
    /**
     * <code>UPLOAD_DATA_BACK = 14;</code>
     */
    public static final int UPLOAD_DATA_BACK_VALUE = 14;


    public final int getNumber() {
      return value;
    }

    public static CommandType valueOf(int value) {
      switch (value) {
        case 1:
          return AUTH;
        case 2:
          return PING;
        case 3:
          return PUSH_DATA;
        case 4:
          return UPLOAD_DATA;
        case 11:
          return AUTH_BACK;
        case 12:
          return PONG;
        case 13:
          return PUSH_DATA_BACK;
        case 14:
          return UPLOAD_DATA_BACK;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
    internalGetValueMap() {
      return internalValueMap;
    }

    private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
          public CommandType findValueByNumber(int number) {
            return CommandType.valueOf(number);
          }
        };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return com.weds.socket.protobuf.Command.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CommandType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CommandType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  static {
    java.lang.String[] descriptorData = {
        "\n\rCommand.proto*\204\001\n\013CommandType\022\010\n\004AUTH\020" +
            "\001\022\010\n\004PING\020\002\022\r\n\tPUSH_DATA\020\003\022\017\n\013UPLOAD_DAT" +
            "A\020\004\022\r\n\tAUTH_BACK\020\013\022\010\n\004PONG\020\014\022\022\n\016PUSH_DAT" +
            "A_BACK\020\r\022\024\n\020UPLOAD_DATA_BACK\020\016B#\n\030com.we" +
            "ds.socket.protobufB\007Command"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[]{
            }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
